### ISSUE TITLE
cannot find module when running CMC lambda function

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giv-supply-function#4]
While trying to run the `node lambda-run` script for index.js for updating the CMC related files i get an error related to "cannot find module"

![image](https://github.com/user-attachments/assets/b74f9951-dfb0-489a-9d97-92a7ec00bdab)

cc: @laurenluz

**Comment by divine-comedian** [comment]
@aminlatifi - for you!

**Comment by aminlatifi** [comment]
@divine-comedian I switched to coingecko directory and it worked
<img width="1328" alt="image" src="https://github.com/user-attachments/assets/9e008960-a5ae-4a93-a878-5db04a9c5c04">

**Comment by divine-comedian** [comment]
> @divine-comedian I switched to coingecko directory and it worked <img alt="image" width="1328" src="https://private-user-images.githubusercontent.com/5684607/351036189-9e008960-a5ae-4a93-a878-5db04a9c5c04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Njk3MjMsIm5iZiI6MTcyMTY2OTQyMywicGF0aCI6Ii81Njg0NjA3LzM1MTAzNjE4OS05ZTAwODk2MC1hNWFlLTRhOTMtYTg3OC01ZGIwNGE5YzVjMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTczMDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTIxYzViOGIyNTUzODhjZTViYmM0ZDcxZjA4ZjlkNTBjY2FjZjk3YjVlZDk4NzYwMWU0M2I3MjljZDVhMzk5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tB1U7IWCes6R8HuiM_dJshfW9nquL4qjf-35wJoePfA">

Yes it worked for me too on coingecko but AFAIK we need to run the function on both folders - CMC and coingecko then upload the files to the repo

**Comment by aminlatifi** [comment]
@divine-comedian please look at this
https://github.com/Giveth/giv-supply-function/pull/6
`event.json` is the default event passed to lambda function. As I understood, it simulates the event parameter passed to the function when it's called.
The two valid event to call coinmarketcap are 
```json
{
  "queryStringParameters": {
    "q": "circulating"
  }
}
```
and 
```json
{
  "queryStringParameters": {
    "q": "totalcoins"
  }
}
```
you can run it with either of events depending on your need.

**Comment by divine-comedian** [comment]
OK - please let me know when it can be tested it again - I see the pending PR

**Comment by divine-comedian** [comment]
I just re-tested this with using `node-lambda run` for both coingecko and CMC and I did not encounter any errors!
